spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manual?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: 8081
  ssl:
    enabled: true
    key-store: src/main/resources/pysicalguide.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: pysicalguide